import type { Product, Category } from "./types"

// Mock product data with all categories
const products: Product[] = [
  //lifestyle
 {
    id: "lifestyle-1",
    name: "Stainless Steel Oil Filter Pot with Tray Large Capacity",
    description:
      "Heat-insulated Handle: Features a heat-insulated wooden handle for safe pouring of hot oil directly into the pot. Material: Crafted from durable stainless steel with a heat-resistant wooden handle for safe handling. Safety: Comes with a dust-proof lid to maintain the cleanliness of stored cooking oil. Convenience: Equipped with a removable fine-mesh filter to strain out food particles from used oil.",
    price: 29.99,
    originalPrice: 39.99,
    images: [
      "/img/style_main.jpg",
      "/img/style_1.jpg",
      "/img/style_2.jpg",
      "/img/style_3.jpg",
    ],
    category: "lifestyle",
    brand: "Nordic Home",
    rating: 4.8,
    reviews: 12,
    reviewCount: 12,
    inStock: true,
    isNewArrival: true,
    isFeatured: true,
    discount: 25,
    freeShipping: true,
    tags: ["oil filter", "stainless steel", "kitchen", "cookware"],
  },
 
  {
    id: "lifestyle-2",
    name: "Luxury Cashmere Siesta Blanket",
    description: "Suitable for sofas, sofas, chairs, cars, cribs and air-conditioned rooms, or across the end of the bed to add extra texture to your living room.Ultra-soft, breathable, warm, comfortable, durable, hypoallergenic and light weight. It does not wrinkle, does not fade, and is suitable for any season.Elegance-add extra texture to your home decoration, and comfortable leisure appearance provides you with a luxurious quality of life.Easy to care for-made of anti-shrinkage fabric. Gently circulate the machine to wash cold water. Roll and dry over low heat. No bleaching",
    price: 19.99,
    originalPrice: 24.99,
    images: [
      "/img/lifestyle-2-1.jpg",
      "/img/lifestyle-2-2.jpg",
      "/img/lifestyle-2-3.jpg",
      "/img/lifestyle-2-4.jpg",
    ],
    category: "lifestyle",
    brand: "Comfort Co",
    rating: 4.9,
    reviews: 13,
    reviewCount: 13,
    inStock: true,
    isNewArrival: false,
    isFeatured: true,
    discount: 25,
    freeShipping: true,
    tags: ["cashmere", "throw", "blanket", "luxury"],
  },
  {
    id: "lifestyle-3",
    name: "Brass Mirror Round",
    description: "Elegant round mirror with brass frame. Perfect for entryways, bathrooms, or as an accent piece.",
    price: 59.99,
    originalPrice: null,
    images: [
      "/img/lifestyle-3-1.jpg",
      "/img/lifestyle-3-2.jpg",
      "/img/lifestyle-3-3.jpg",
      "/img/lifestyle-3-4.jpg",
    ],
    category: "lifestyle",
    brand: "Reflection",
    rating: 4.7,
    reviews: 23,
    reviewCount: 23,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["mirror", "brass", "round", "decor"],
  },
  {
    id: "lifestyle-4",
    name: "Walnut Coffee Table",
    description: "Mid-century modern coffee table crafted from solid walnut wood. Features clean lines and timeless design.",
    price: 499.99,
    originalPrice: null,
    images: [
      "/img/lifestyle-4-1.jpg",
      "/img/lifestyle-4-2.jpg",
      "/img/lifestyle-4-3.jpg",
      "/img/lifestyle-4-4.jpg",
    ],
    category: "lifestyle",
    brand: "Wood Works",
    rating: 4.8,
    reviews: 6,
    reviewCount: 7,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["coffee table", "walnut", "mid-century", "furniture"],
  },
  {
    id: "lifestyle-5",
    name: "Handwoven Jute Rug",
    description: "Natural jute rug with intricate weave patterns, adding texture and warmth to any room.",
    price: 15.99,
    originalPrice: 29.99,
    images: [
      "/img/lifestyle-5-1.jpg",
      "/img/lifestyle-5-2.jpg",
      "/img/lifestyle-5-3.jpg",
      "/img/lifestyle-5-4.jpg",
    ],
    category: "lifestyle",
    brand: "Earthy Threads",
    rating: 4.6,
    reviews: 27,
    reviewCount: 27,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 16.67,
    freeShipping: true,
    tags: ["rug", "jute", "handwoven", "home decor"],
  },
  {
    id: "lifestyle-6",
    name: "Marble Coaster Set",
    description: "Set of four polished marble coasters with gold accents, perfect for protecting surfaces in style.",
    price: 19.99,
    originalPrice: null,
    images: [
      "/img/lifestyle-6-1.jpg",
      "/img/lifestyle-6-2.jpg",
      "/img/lifestyle-6-3.jpg",
      "/img/lifestyle-6-4.jpg",
    ],
    category: "lifestyle",
    brand: "Stone Elegance",
    rating: 4.5,
    reviews: 10,
    reviewCount: 10,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["coasters", "marble", "gold accent", "tableware"],
  },
  {
    id: "lifestyle-7",
    name: "Velvet Accent Pillow",
    description: "Luxurious velvet pillow in deep emerald green, adding a pop of color and comfort to sofas or beds.",
    price: 19.99,
    originalPrice: 29.99,
    images: [
      "/img/lifestyle-7-1.jpg",
      "/img/lifestyle-7-2.jpg",
      "/img/lifestyle-7-3.jpg",
      "/img/lifestyle-7-4.jpg",
    ],
    category: "lifestyle",
    brand: "Comfort Co",
    rating: 4.7,
    reviews: 9,
    reviewCount: 9,
    inStock: true,
    isNewArrival: false,
    isFeatured: true,
    discount: 25,
    freeShipping: true,
    tags: ["pillow", "velvet", "accent", "home decor"],
  },
  {
    id: "lifestyle-8",
    name: "Bamboo Wall Shelf",
    description: "Minimalist bamboo wall shelf, ideal for displaying plants, books, or decorative items.",
    price: 59.99,
    originalPrice: null,
    images: [
      "/img/lifestyle-8-1.jpg",
      "/img/lifestyle-8-2.jpg",
      "/img/lifestyle-8-3.jpg",
      "/img/lifestyle-8-4.jpg",
    ],
    category: "lifestyle",
    brand: "Eco Living",
    rating: 4.4,
    reviews: 3,
    reviewCount: 3,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["shelf", "bamboo", "wall decor", "storage"],
  },
  {
    id: "lifestyle-9",
    name: "Scented Soy Candle",
    description: "Hand-poured soy candle with lavender and cedarwood notes, housed in a sleek glass jar.",
    price: 29.99,
    originalPrice: null,
    images: [
      "/img/lifestyle-9-1.jpg",
      "/img/lifestyle-9-2.jpg",
      "/img/lifestyle-9-3.jpg",
      "/img/lifestyle-9-4.jpg",
    ],
    category: "lifestyle",
    brand: "Glow Essence",
    rating: 4.9,
    reviews: 145,
    reviewCount: 145,
    inStock: true,
    isNewArrival: true,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["candle", "soy", "scented", "home decor"],
  },
  {
    id: "lifestyle-10",
    name: "Linen Bedding Set",
    description: "Skin-Friendly Design The skin-friendly fabric of this duvet cover set is gentle on your skin, providing a soft and cozy sleeping experience.Attractive Flower Branch Design Featuring a beautiful flower branch design, this duvet cover adds a touch of elegance and sophistication to your bedroom decor.Complete Bedding Set This complete bedding set includes everything you need to refresh your bedroom, including a duvet cover and matching pillowcases.Queen Size Compatibility Designed specifically for queen-size beds, this duvet cover set offers a perfect fit and coverage.Easy Care This duvet cover is easy to care for, making it a practical choice for busy lifestyles.",
    price: 49.99,
    originalPrice: 69.99,
    images: [
      "/img/lifestyle-10-1.jpg",
      "/img/lifestyle-10-2.jpg",
      "/img/lifestyle-10-3.jpg",
      "/img/lifestyle-10-4.jpg",
    ],
    category: "lifestyle",
    brand: "Pure Rest",
    rating: 4.8,
    reviews: 20,
    reviewCount: 20,
    inStock: true,
    isNewArrival: false,
    isFeatured: true,
    discount: 18.6,
    freeShipping: true,
    tags: ["bedding", "linen", "duvet", "bedroom"],
  },
  {
    id: "lifestyle-11",
    name: "Terrazzo Side Table",
    description: "Modern terrazzo side table with a speckled finish, perfect for small spaces or as a bedside accent.",
    price: 199.99,
    originalPrice: null,
    images: [
      "/img/lifestyle-11-1.jpg",
      "/img/lifestyle-11-2.jpg",
      "/img/lifestyle-11-3.jpg",
      "/img/lifestyle-11-4.jpg",
    ],
    category: "lifestyle",
    brand: "Urban Craft",
    rating: 4.6,
    reviews: 64,
    reviewCount: 64,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["side table", "terrazzo", "modern", "furniture"],
  },
  {
    id: "lifestyle-12",
    name: "Ceramic Table Lamp",
    description: "Sculptural ceramic table lamp with a matte finish and linen shade, ideal for cozy lighting.",
    price: 139.99,
    originalPrice: null,
    images: [
      "/img/lifestyle-12-1.jpg",
      "/img/lifestyle-12-2.jpg",
      "/img/lifestyle-12-3.jpg",
      "/img/lifestyle-12-4.jpg",
    ],
    category: "lifestyle",
    brand: "Light Haven",
    rating: 4.7,
    reviews: 88,
    reviewCount: 88,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["lamp", "ceramic", "lighting", "home decor"],
  },
  {
    id: "lifestyle-13",
    name: "Woven Basket Set",
    description: "Set of three woven seagrass baskets for stylish storage of blankets, toys, or plants.",
    price: 79.99,
    originalPrice: null,
    images: [
      "/img/lifestyle-13-1.jpg",
      "/img/lifestyle-13-2.jpg",
      "/img/lifestyle-13-3.jpg",
      "/img/lifestyle-13-4.jpg",
    ],
    category: "lifestyle",
    brand: "Natural Nest",
    rating: 4.5,
    reviews: 47,
    reviewCount: 47,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["basket", "seagrass", "storage", "home decor"],
  },
  {
    id: "lifestyle-14",
    name: "Glass Decanter Set",
    description: "Elegant glass decanter with two matching glasses, perfect for serving whiskey or wine.",
    price: 99.99,
    originalPrice: 129.99,
    images: [
      "/img/lifestyle-14-1.jpg",
      "/img/lifestyle-14-2.jpg",
      "/img/lifestyle-14-3.jpg",
      "/img/lifestyle-14-4.jpg",
    ],
    category: "lifestyle",
    brand: "Crystal Craft",
    rating: 4.8,
    reviews: 76,
    reviewCount: 76,
    inStock: true,
    isNewArrival: true,
    isFeatured: false,
    discount: 23.08,
    freeShipping: true,
    tags: ["decanter", "glassware", "barware", "luxury"],
  },
  {
    id: "lifestyle-15",
    name: "Teak Wood Cutting Board",
    description: "Durable teak wood cutting board with natural grain, perfect for food prep or serving.",
    price: 49.99,
    originalPrice: null,
    images: [
      "/img/lifestyle-15-1.jpg",
      "/img/lifestyle-15-2.jpg",
      "/img/lifestyle-15-3.jpg",
      "/img/lifestyle-15-4.jpg",
    ],
    category: "lifestyle",
    brand: "Kitchen Essence",
    rating: 4.6,
    reviews: 112,
    reviewCount: 112,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["cutting board", "teak", "kitchen", "serveware"],
  },
  {
    id: "lifestyle-16",
    name: "Velvet Ottoman",
    description: "Plush velvet ottoman in navy blue, doubling as a footrest or extra seating.",
    price: 249.99,
    originalPrice: null,
    images: [
      "/img/lifestyle-16-1.jpg",
      "/img/lifestyle-16-2.jpg",
      "/img/lifestyle-16-3.jpg",
      "/img/lifestyle-16-4.jpg",
    ],
    category: "lifestyle",
    brand: "Urban Comfort",
    rating: 4.7,
    reviews: 53,
    reviewCount: 53,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["ottoman", "velvet", "furniture", "home decor"],
  },
  {
    id: "lifestyle-17",
    name: "Framed Abstract Art Print",
    description: "Bold abstract art print in a sleek black frame, perfect for modern interiors.",
    price: 39.99,
    originalPrice: 59.99,
    images: [
      "/img/lifestyle-17-1.jpg",
      "/img/lifestyle-17-2.jpg",
      "/img/lifestyle-17-3.jpg",
      "/img/lifestyle-17-4.jpg",
    ],
    category: "lifestyle",
    brand: "Artisan Gallery",
    rating: 4.8,
    reviews: 30,
    reviewCount: 30,
    inStock: true,
    isNewArrival: false,
    isFeatured: true,
    discount: 21.74,
    freeShipping: true,
    tags: ["art print", "abstract", "framed", "wall decor"],
  },
  {
    id: "lifestyle-18",
    name: "Stainless Steel Water Bottle",
    description: "Sleek stainless steel water bottle with double-wall insulation, keeping drinks hot or cold for hours.",
    price: 34.99,
    originalPrice: null,
    images: [
      "/img/lifestyle-18-1.jpg",
      "/img/lifestyle-18-2.jpg",
      "/img/lifestyle-18-3.jpg",
      "/img/lifestyle-18-4.jpg",
    ],
    category: "lifestyle",
    brand: "Eco Sip",
    rating: 4.5,
    reviews: 134,
    reviewCount: 134,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["water bottle", "stainless steel", "insulated", "eco-friendly"],
  },
  {
    id: "lifestyle-19",
    name: "Rattan Armchair",
    description: "Handcrafted rattan armchair with a cushioned seat, blending bohemian and modern styles.",
    price: 499.99,
    originalPrice: null,
    images: [
      "/img/lifestyle-19-1.jpg",
      "/img/lifestyle-19-2.jpg",
      "/img/lifestyle-19-3.jpg",
      "/img/lifestyle-19-4.jpg",
    ],
    category: "lifestyle",
    brand: "Boho Living",
    rating: 4.9,
    reviews: 41,
    reviewCount: 41,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["armchair", "rattan", "bohemian", "furniture"],
  },

  // Wellness Products
  {
    id: "wellness-1",
    name: "Essential Oil Diffuser",
    description:
      "Ultrasonic aromatherapy diffuser with LED lighting. Creates a calming atmosphere while dispersing your favorite essential oils.",
    price: 29.99,
    originalPrice: 49.99,
    images: [
      "/img/wellness-1-1.jpg",
      "/img/wellness-1-2.jpg",
      "/img/wellness-1-3.jpg",
      "/img/wellness-1-4.jpg",
    ],
    category: "wellness",
    brand: "Zen Living",
    rating: 4.6,
    reviews: 25,
    reviewCount: 25,
    inStock: true,
    isNewArrival: true,
    isFeatured: true,
    discount: 40,
    freeShipping: true,
    tags: ["diffuser", "aromatherapy", "wellness", "essential oils"],
  },
  {
    id: "wellness-2",
    name: "Premium Yoga Mat",
    description:
      "Non-slip yoga mat made from natural rubber. Provides excellent grip and cushioning for all yoga practices.",
    price: 89.99,
    originalPrice: null,
    images: [
      "/img/wellness-2-1.jpg",
      "/img/wellness-2-2.jpg",
      "/img/wellness-2-3.jpg",
      "/img/wellness-2-4.jpg",
    ],
    category: "wellness",
    brand: "Mindful Movement",
    rating: 4.8,
    reviews: 156,
    reviewCount: 156,
    inStock: true,
    isNewArrival: false,
    isFeatured: true,
    discount: 0,
    freeShipping: true,
    tags: ["yoga", "mat", "exercise", "wellness"],
  },
  {
    id: "wellness-3",
    name: "Meditation Cushion",
    description:
      "Comfortable meditation cushion filled with buckwheat hulls. Supports proper posture during meditation practice.",
    price: 59.99,
    originalPrice: null,
    images: [
      "/img/wellness-3-1.jpg",
      "/img/wellness-3-2.jpg",
      "/img/wellness-3-3.jpg",
      "/img/wellness-3-4.jpg",
    ],
    category: "wellness",
    brand: "Inner Peace",
    rating: 4.7,
    reviews: 92,
    reviewCount: 92,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["meditation", "cushion", "mindfulness", "wellness"],
  },
  {
    id: "wellness-4",
    name: "Weighted Blanket",
    description: "15-pound weighted blanket with breathable cotton cover. Promotes relaxation and better sleep.",
    price: 129.99,
    originalPrice: 159.99,
    images: [
      "/img/wellness-4-1.jpg",
      "/img/wellness-4-2.jpg",
      "/img/wellness-4-3.jpg",
      "/img/wellness-4-4.jpg",
    ],
    category: "wellness",
    brand: "Calm Comfort",
    rating: 4.9,
    reviews: 84,
    reviewCount: 84,
    inStock: true,
    isNewArrival: true,
    isFeatured: true,
    discount: 18.75,
    freeShipping: true,
    tags: ["weighted blanket", "sleep", "relaxation", "wellness"],
  },
  {
    id: "wellness-5",
    name: "Aromatherapy Essential Oil Set",
    description: "Set of six pure essential oils (lavender, eucalyptus, peppermint, etc.) for diffusers or topical use.",
    price: 39.99,
    originalPrice: null,
    images: [
      "/img/wellness-5-1.jpg",
      "/img/wellness-5-2.jpg",
      "/img/wellness-5-3.jpg",
      "/img/wellness-5-4.jpg",
    ],
    category: "wellness",
    brand: "Zen Living",
    rating: 4.5,
    reviews: 63,
    reviewCount: 63,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["essential oils", "aromatherapy", "wellness", "relaxation"],
  },
  {
    id: "wellness-6",
    name: "Foam Roller",
    description: "High-density foam roller for muscle recovery and flexibility. Ideal for post-workout relief.",
    price: 34.99,
    originalPrice: null,
    images: [
      "/img/wellness-6-1.jpg",
      "/img/wellness-6-2.jpg",
      "/img/wellness-6-3.jpg",
      "/img/wellness-6-4.jpg",
    ],
    category: "wellness",
    brand: "Fit Recovery",
    rating: 4.6,
    reviews: 77,
    reviewCount: 77,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["foam roller", "fitness", "recovery", "wellness"],
  },
  {
    id: "wellness-7",
    name: "Himalayan Salt Lamp",
    description: "Hand-carved Himalayan salt lamp with dimmable glow. Creates a soothing ambiance.",
    price: 49.99,
    originalPrice: 69.99,
    images: [
      "/img/wellness-7-1.jpg",
      "/img/wellness-7-2.jpg",
      "/img/wellness-7-3.jpg",
      "/img/wellness-7-4.jpg",
    ],
    category: "wellness",
    brand: "Glow Essence",
    rating: 4.7,
    reviews: 105,
    reviewCount: 105,
    inStock: true,
    isNewArrival: true,
    isFeatured: true,
    discount: 28.57,
    freeShipping: true,
    tags: ["salt lamp", "ambiance", "wellness", "relaxation"],
  },
  {
    id: "wellness-8",
    name: "Acupressure Mat and Pillow",
    description: "Acupressure mat and pillow set for pain relief and relaxation. Stimulates pressure points.",
    price: 79.99,
    originalPrice: null,
    images: [
      "/img/wellness-8-1.jpg",
      "/img/wellness-8-2.jpg",
      "/img/wellness-8-3.jpg",
      "/img/wellness-8-4.jpg",
    ],
    category: "wellness",
    brand: "Inner Peace",
    rating: 4.8,
    reviews: 88,
    reviewCount: 88,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["acupressure", "pain relief", "wellness", "relaxation"],
  },
  {
    id: "wellness-9",
    name: "Herbal Tea Blend Set",
    description: "Set of three herbal tea blends (chamomile, peppermint, lavender) for calming and wellness.",
    price: 24.99,
    originalPrice: null,
    images: [
      "/img/wellness-9-1.jpg",
      "/img/wellness-9-2.jpg",
      "/img/wellness-9-3.jpg",
      "/img/wellness-9-4.jpg",
    ],
    category: "wellness",
    brand: "Pure Bliss",
    rating: 4.6,
    reviews: 52,
    reviewCount: 52,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["herbal tea", "wellness", "relaxation", "beverage"],
  },
  {
    id: "wellness-10",
    name: "Massage Gun",
    description: "Portable massage gun with multiple speed settings for muscle recovery and relaxation.",
    price: 129.99,
    originalPrice: 179.99,
    images: [
      "/img/wellness-10-1.jpg",
      "/img/wellness-10-2.jpg",
      "/img/wellness-10-3.jpg",
      "/img/wellness-10-4.jpg",
    ],
    category: "wellness",
    brand: "Fit Recovery",
    rating: 4.9,
    reviews: 123,
    reviewCount: 123,
    inStock: true,
    isNewArrival: true,
    isFeatured: true,
    discount: 27.78,
    freeShipping: true,
    tags: ["massage gun", "recovery", "wellness", "fitness"],
  },
  {
    id: "wellness-11",
    name: "Sleep Mask",
    description: "Silk sleep mask with adjustable strap for comfortable, light-blocking sleep.",
    price: 19.99,
    originalPrice: null,
    images: [
      "/img/wellness-11-1.jpg",
      "/img/wellness-11-2.jpg",
      "/img/wellness-11-3.jpg",
      "/img/wellness-11-4.jpg",
    ],
    category: "wellness",
    brand: "Calm Comfort",
    rating: 4.5,
    reviews: 95,
    reviewCount: 95,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["sleep mask", "silk", "wellness", "sleep"],
  },
  {
    id: "wellness-12",
    name: "Sound Machine",
    description: "White noise and nature sound machine with adjustable volume for better sleep or focus.",
    price: 44.99,
    originalPrice: null,
    images: [
      "/img/wellness-12-1.jpg",
      "/img/wellness-12-2.jpg",
      "/img/wellness-12-3.jpg",
      "/img/wellness-12-4.jpg",
    ],
    category: "wellness",
    brand: "Zen Living",
    rating: 4.7,
    reviews: 67,
    reviewCount: 67,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["sound machine", "white noise", "wellness", "sleep"],
  },
  {
    id: "wellness-13",
    name: "Balance Board",
    description: "Wooden balance board for core strength and stability training. Ideal for home workouts.",
    price: 69.99,
    originalPrice: 89.99,
    images: [
      "/img/wellness-13-1.jpg",
      "/img/wellness-13-2.jpg",
      "/img/wellness-13-3.jpg",
      "/img/wellness-13-4.jpg",
    ],
    category: "wellness",
    brand: "Fit Recovery",
    rating: 4.6,
    reviews: 55,
    reviewCount: 55,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 22.22,
    freeShipping: true,
    tags: ["balance board", "fitness", "core strength", "wellness"],
  },
  {
    id: "wellness-14",
    name: "Journal Notebook",
    description: "Guided wellness journal with prompts for mindfulness and gratitude. Faux leather cover.",
    price: 29.99,
    originalPrice: null,
    images: [
      "/img/wellness-14-1.jpg",
      "/img/wellness-14-2.jpg",
      "/img/wellness-14-3.jpg",
      "/img/wellness-14-4.jpg",
    ],
    category: "wellness",
    brand: "Inner Peace",
    rating: 4.5,
    reviews: 70,
    reviewCount: 70,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["journal", "mindfulness", "wellness", "gratitude"],
  },
  {
    id: "wellness-15",
    name: "Neck Massager",
    description: "Portable neck massager with heat and adjustable intensity for tension relief.",
    price: 99.99,
    originalPrice: 129.99,
    images: [
      "/img/wellness-15-1.jpg",
      "/img/wellness-15-2.jpg",
      "/img/wellness-15-3.jpg",
      "/img/wellness-15-4.jpg",
    ],
    category: "wellness",
    brand: "Calm Comfort",
    rating: 4.8,
    reviews: 82,
    reviewCount: 82,
    inStock: true,
    isNewArrival: true,
    isFeatured: false,
    discount: 23.08,
    freeShipping: true,
    tags: ["neck massager", "relaxation", "wellness", "massage"],
  },
 // Electronics Products
  {
    id: "electronics-1",
    name: "Wireless Noise-Canceling Headphones",
    description:
      "Premium wireless headphones with active noise cancellation. Delivers exceptional sound quality and comfort.",
    price: 299.99,
    originalPrice: 399.99,
    images: [
      "/img/electronics-1-1.jpg",
      "/img/electronics-1-2.jpg",
      "/img/electronics-1-3.jpg",
      "/img/electronics-1-4.jpg",
    ],
    category: "electronics",
    brand: "SoundTech",
    rating: 4.9,
    reviews: 342,
    reviewCount: 342,
    inStock: true,
    isNewArrival: false,
    isFeatured: true,
    discount: 25,
    freeShipping: true,
    tags: ["headphones", "wireless", "noise-canceling", "audio"],
  },
  {
    id: "electronics-2",
    name: "Smart Fitness Watch",
    description:
      "Advanced fitness tracker with heart rate monitoring, GPS, and smartphone connectivity. Perfect for active lifestyles.",
    price: 249.99,
    originalPrice: null,
    images: [
      "/img/electronics-2-1.jpg",
      "/img/electronics-2-2.jpg",
      "/img/electronics-2-3.jpg",
      "/img/electronics-2-4.jpg",
    ],
    category: "electronics",
    brand: "FitTech",
    rating: 4.7,
    reviews: 189,
    reviewCount: 189,
    inStock: true,
    isNewArrival: true,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["smartwatch", "fitness", "tracker", "health"],
  },
  {
    id: "electronics-3",
    name: "Portable Bluetooth Speaker",
    description:
      "Compact wireless speaker with powerful sound and long battery life. Perfect for outdoor adventures and home use.",
    price: 129.99,
    originalPrice: null,
    images: [
      "/img/electronics-3-1.jpg",
      "/img/electronics-3-2.jpg",
      "/img/electronics-3-3.jpg",
      "/img/electronics-3-4.jpg",
    ],
    category: "electronics",
    brand: "AudioWave",
    rating: 4.6,
    reviews: 267,
    reviewCount: 267,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["speaker", "bluetooth", "portable", "audio"],
  },
  {
    id: "electronics-4",
    name: "Wireless Charging Pad",
    description: "Fast wireless charging pad compatible with all Qi-enabled devices. Sleek and compact design.",
    price: 39.99,
    originalPrice: null,
    images: [
      "/img/electronics-4-1.jpg",
      "/img/electronics-4-2.jpg",
      "/img/electronics-4-3.jpg",
      "/img/electronics-4-4.jpg",
    ],
    category: "electronics",
    brand: "TechTrend",
    rating: 4.5,
    reviews: 150,
    reviewCount: 150,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["charger", "wireless", "electronics", "accessory"],
  },
  {
    id: "electronics-5",
    name: "Smart Home Hub",
    description: "Central hub for controlling smart home devices. Compatible with Alexa and Google Home.",
    price: 149.99,
    originalPrice: 199.99,
    images: [
      "/img/electronics-5-1.jpg",
      "/img/electronics-5-2.jpg",
      "/img/electronics-5-3.jpg",
      "/img/electronics-5-4.jpg",
    ],
    category: "electronics",
    brand: "SmartTech",
    rating: 4.8,
    reviews: 210,
    reviewCount: 210,
    inStock: true,
    isNewArrival: true,
    isFeatured: true,
    discount: 25,
    freeShipping: true,
    tags: ["smart hub", "home automation", "electronics", "smart home"],
  },
  {
    id: "electronics-6",
    name: "4K Action Camera",
    description: "Compact 4K action camera with waterproof housing. Ideal for capturing adventures.",
    price: 199.99,
    originalPrice: null,
    images: [
      "/img/electronics-6-1.jpg",
      "/img/electronics-6-2.jpg",
      "/img/electronics-6-3.jpg",
      "/img/electronics-6-4.jpg",
    ],
    category: "electronics",
    brand: "AdventureTech",
    rating: 4.7,
    reviews: 175,
    reviewCount: 175,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["action camera", "4K", "electronics", "adventure"],
  },
  {
    id: "electronics-7",
    name: "Wireless Earbuds",
    description: "True wireless earbuds with noise cancellation and long battery life. Perfect for on-the-go audio.",
    price: 99.99,
    originalPrice: 129.99,
    images: [
      "/img/electronics-7-1.jpg",
      "/img/electronics-7-2.jpg",
      "/img/electronics-7-3.jpg",
      "/img/electronics-7-4.jpg",
    ],
    category: "electronics",
    brand: "SoundTech",
    rating: 4.6,
    reviews: 230,
    reviewCount: 230,
    inStock: true,
    isNewArrival: true,
    isFeatured: false,
    discount: 23.08,
    freeShipping: true,
    tags: ["earbuds", "wireless", "noise-canceling", "audio"],
  },
  {
    id: "electronics-8",
    name: "Smart LED Bulb Set",
    description: "Set of four smart LED bulbs with color-changing and dimmable features. App-controlled.",
    price: 59.99,
    originalPrice: null,
    images: [
      "/img/electronics-8-1.jpg",
      "/img/electronics-8-2.jpg",
      "/img/electronics-8-3.jpg",
      "/img/electronics-8-4.jpg",
    ],
    category: "electronics",
    brand: "LightTech",
    rating: 4.5,
    reviews: 145,
    reviewCount: 145,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["smart bulb", "lighting", "electronics", "smart home"],
  },
  {
    id: "electronics-9",
    name: "Portable Power Bank",
    description: "High-capacity 20,000mAh power bank with fast charging. Ideal for travel and emergencies.",
    price: 49.99,
    originalPrice: null,
    images: [
      "/img/electronics-9-1.jpg",
      "/img/electronics-9-2.jpg",
      "/img/electronics-9-3.jpg",
      "/img/electronics-9-4.jpg",
    ],
    category: "electronics",
    brand: "TechTrend",
    rating: 4.6,
    reviews: 190,
    reviewCount: 190,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["power bank", "charger", "electronics", "portable"],
  },
  {
    id: "electronics-10",
    name: "Smart Thermostat",
    description: "Energy-saving smart thermostat with remote control and learning features. Wi-Fi enabled.",
    price: 179.99,
    originalPrice: 229.99,
    images: [
      "/img/electronics-10-1.jpg",
      "/img/electronics-10-2.jpg",
      "/img/electronics-10-3.jpg",
      "/img/electronics-10-4.jpg",
    ],
    category: "electronics",
    brand: "SmartTech",
    rating: 4.8,
    reviews: 165,
    reviewCount: 165,
    inStock: true,
    isNewArrival: true,
    isFeatured: true,
    discount: 21.74,
    freeShipping: true,
    tags: ["thermostat", "smart home", "electronics", "energy-saving"],
  },
  {
    id: "electronics-11",
    name: "Mini Projector",
    description: "Portable mini projector with HD resolution. Perfect for home theater or presentations.",
    price: 299.99,
    originalPrice: null,
    images: [
      "/img/electronics-11-1.jpg",
      "/img/electronics-11-2.jpg",
      "/img/electronics-11-3.jpg",
      "/img/electronics-11-4.jpg",
    ],
    category: "electronics",
    brand: "VisionTech",
    rating: 4.7,
    reviews: 130,
    reviewCount: 130,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["projector", "home theater", "electronics", "portable"],
  },
  {
    id: "electronics-12",
    name: "Smart Doorbell",
    description: "Wi-Fi smart doorbell with HD camera and motion detection. Enhances home security.",
    price: 149.99,
    originalPrice: 199.99,
    images: [
      "/img/electronics-12-1.jpg",
      "/img/electronics-12-2.jpg",
      "/img/electronics-12-3.jpg",
      "/img/electronics-12-4.jpg",
    ],
    category: "electronics",
    brand: "SecureTech",
    rating: 4.8,
    reviews: 200,
    reviewCount: 200,
    inStock: true,
    isNewArrival: true,
    isFeatured: false,
    discount: 25,
    freeShipping: true,
    tags: ["door bell", "smart home", "electronics", "security"],
  },
  {
    id: "electronics-13",
    name: "Wireless Keyboard and Mouse",
    description: "Ergonomic wireless keyboard and mouse combo with long battery life. Ideal for work or gaming.",
    price: 79.99,
    originalPrice: null,
    images: [
      "/img/electronics-13-1.jpg",
      "/img/electronics-13-2.jpg",
      "/img/electronics-13-3.jpg",
      "/img/electronics-13-4.jpg",
    ],
    category: "electronics",
    brand: "TechTrend",
    rating: 4.6,
    reviews: 155,
    reviewCount: 155,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["keyboard", "mouse", "wireless", "electronics"],
  },
  {
    id: "electronics-14",
    name: "Smart Scale",
    description: "Bluetooth smart scale with body composition analysis. Tracks weight, BMI, and more.",
    price: 69.99,
    originalPrice: null,
    images: [
      "/img/electronics-14-1.jpg",
      "/img/electronics-14-2.jpg",
      "/img/electronics-14-3.jpg",
      "/img/electronics-14-4.jpg",
    ],
    category: "electronics",
    brand: "FitTech",
    rating: 4.5,
    reviews: 140,
    reviewCount: 140,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["smart scale", "fitness", "electronics", "health"],
  },
  {
    id: "electronics-15",
    name: "USB-C Hub",
    description: "Multi-port USB-C hub with HDMI, USB, and SD card slots. Perfect for laptop connectivity.",
    price: 49.99,
    originalPrice: null,
    images: [
      "/img/electronics-15-1.jpg",
      "/img/electronics-15-2.jpg",
      "/img/electronics-15-3.jpg",
      "/img/electronics-15-4.jpg",
    ],
    category: "electronics",
    brand: "TechTrend",
    rating: 4.6,
    reviews: 170,
    reviewCount: 170,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["usb hub", "electronics", "connectivity", "accessory"],
  },
  // Fashion Products
  {
    id: "fashion-1",
    name: "Silk Scarf Collection",
    description: "Luxurious silk scarf with hand-painted design. Adds elegance to any outfit and makes a perfect gift.",
    price: 149.99,
    originalPrice: 199.99,
    images: [
      "/img/fashion-1-1.jpg",
      "/img/fashion-1-2.jpg",
      "/img/fashion-1-3.jpg",
      "/img/fashion-1-4.jpg",
    ],
    category: "fashion",
    brand: "Elegance",
    rating: 4.8,
    reviews: 78,
    reviewCount: 78,
    inStock: true,
    isNewArrival: false,
    isFeatured: true,
    discount: 25,
    freeShipping: true,
    tags: ["scarf", "silk", "fashion", "accessory"],
  },
  {
    id: "fashion-2",
    name: "Designer Handbag",
    description: "Premium leather handbag with modern design. Features multiple compartments and adjustable strap.",
    price: 399.99,
    originalPrice: null,
    images: [
      "/img/fashion-2-1.jpg",
      "/img/fashion-2-2.jpg",
      "/ Kimg/fashion-2-3.jpg",
      "/img/fashion-2-4.jpg",
    ],
    category: "fashion",
    brand: "Luxe Bags",
    rating: 4.9,
    reviews: 134,
    reviewCount: 134,
    inStock: true,
    isNewArrival: false,
    isFeatured: true,
    discount: 0,
    freeShipping: true,
    tags: ["handbag", "leather", "designer", "fashion"],
  },
  {
    id: "fashion-3",
    name: "Polarized Sunglasses",
    description:
      "Stylish sunglasses with polarized lenses and UV protection. Perfect for outdoor activities and fashion.",
    price: 179.99,
    originalPrice: null,
    images: [
      "/img/fashion-3-1.jpg",
      "/img/fashion-3-2.jpg",
      "/img/fashion-3-3.jpg",
      "/img/fashion-3-4.jpg",
    ],
    category: "fashion",
    brand: "SunStyle",
    rating: 4.7,
    reviews: 156,
    reviewCount: 156,
    inStock: true,
    isNewArrival: true,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["sunglasses", "polarized", "fashion", "accessory"],
  },
  {
    id: "fashion-4",
    name: "Cashmere Sweater",
    description: "Soft cashmere sweater in neutral tones. Perfect for layering and everyday elegance.",
    price: 249.99,
    originalPrice: 299.99,
    images: [
      "/img/fashion-4-1.jpg",
      "/img/fashion-4-2.jpg",
      "/img/fashion-4-3.jpg",
      "/img/fashion-4-4.jpg",
    ],
    category: "fashion",
    brand: "Elegance",
    rating: 4.8,
    reviews: 110,
    reviewCount: 110,
    inStock: true,
    isNewArrival: false,
    isFeatured: true,
    discount: 16.67,
    freeShipping: true,
    tags: ["sweater", "cashmere", "fashion", "clothing"],
  },
  {
    id: "fashion-5",
    name: "Leather Jacket",
    description: "Classic leather jacket with tailored fit. Timeless style for any wardrobe.",
    price: 499.99,
    originalPrice: null,
    images: [
      "/img/fashion-5-1.jpg",
      "/img/fashion-5-2.jpg",
      "/img/fashion-5-3.jpg",
      "/img/fashion-5-4.jpg",
    ],
    category: "fashion",
    brand: "Luxe Bags",
    rating: 4.9,
    reviews: 145,
    reviewCount: 145,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["jacket", "leather", "fashion", "clothing"],
  },
  {
    id: "fashion-6",
    name: "Woven Tote Bag",
    description: "Handwoven tote bag with leather handles. Spacious and stylish for daily use.",
    price: 129.99,
    originalPrice: null,
    images: [
      "/img/fashion-6-1.jpg",
      "/img/fashion-6-2.jpg",
      "/img/fashion-6-3.jpg",
      "/img/fashion-6-4.jpg",
    ],
    category: "fashion",
    brand: "Artisan Style",
    rating: 4.6,
    reviews: 95,
    reviewCount: 95,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["tote bag", "woven", "fashion", "accessory"],
  },
  {
    id: "fashion-7",
    name: "Minimalist Watch",
    description: "Sleek minimalist watch with stainless steel case and leather strap. Perfect for any occasion.",
    price: 199.99,
    originalPrice: 249.99,
    images: [
      "/img/fashion-7-1.jpg",
      "/img/fashion-7-2.jpg",
      "/img/fashion-7-3.jpg",
      "/img/fashion-7-4.jpg",
    ],
    category: "fashion",
    brand: "TimeCraft",
    rating: 4.7,
    reviews: 120,
    reviewCount: 120,
    inStock: true,
    isNewArrival: true,
    isFeatured: false,
    discount: 20,
    freeShipping: true,
    tags: ["watch", "minimalist", "fashion", "accessory"],
  },
  {
    id: "fashion-8",
    name: "Ankle Boots",
    description: "Stylish leather ankle boots with cushioned insole. Versatile for casual or formal outfits.",
    price: 229.99,
    originalPrice: null,
    images: [
      "/img/fashion-8-1.jpg",
      "/img/fashion-8-2.jpg",
      "/img/fashion-8-3.jpg",
      "/img/fashion-8-4.jpg",
    ],
    category: "fashion",
    brand: "Luxe Bags",
    rating: 4.8,
    reviews: 135,
    reviewCount: 135,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["boots", "leather", "fashion", "footwear"],
  },
  {
    id: "fashion-9",
    name: "Linen Shirt",
    description: "Breathable linen shirt in soft white. Ideal for warm weather and casual elegance.",
    price: 89.99,
    originalPrice: null,
    images: [
      "/img/fashion-9-1.jpg",
      "/img/fashion-9-2.jpg",
      "/img/fashion-9-3.jpg",
      "/img/fashion-9-4.jpg",
    ],
    category: "fashion",
    brand: "Elegance",
    rating: 4.6,
    reviews: 100,
    reviewCount: 100,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["shirt", "linen", "fashion", "clothing"],
  },
  {
    id: "fashion-10",
    name: "Statement Necklace",
    description: "Bold statement necklace with gemstone accents. Elevates any outfit with elegance.",
    price: 79.99,
    originalPrice: 99.99,
    images: [
      "/img/fashion-10-1.jpg",
      "/img/fashion-10-2.jpg",
      "/img/fashion-10-3.jpg",
      "/img/fashion-10-4.jpg",
    ],
    category: "fashion",
    brand: "Artisan Style",
    rating: 4.7,
    reviews: 85,
    reviewCount: 85,
    inStock: true,
    isNewArrival: true,
    isFeatured: false,
    discount: 20,
    freeShipping: true,
    tags: ["necklace", "jewelry", "fashion", "accessory"],
  },
  {
    id: "fashion-11",
    name: "Wool Fedora Hat",
    description: "Classic wool fedora hat with modern styling. Perfect for adding sophistication to any look.",
    price: 69.99,
    originalPrice: null,
    images: [
      "/img/fashion-11-1.jpg",
      "/img/fashion-11-2.jpg",
      "/img/fashion-11-3.jpg",
      "/img/fashion-11-4.jpg",
    ],
    category: "fashion",
    brand: "SunStyle",
    rating: 4.6,
    reviews: 90,
    reviewCount: 90,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["hat", "fedora", "fashion", "accessory"],
  },
  {
    id: "fashion-12",
    name: "Tailored Blazer",
    description: "Slim-fit tailored blazer in navy. Ideal for professional or evening wear.",
    price: 349.99,
    originalPrice: 429.99,
    images: [
      "/img/fashion-12-1.jpg",
      "/img/fashion-12-2.jpg",
      "/img/fashion-12-3.jpg",
      "/img/fashion-12-4.jpg",
    ],
    category: "fashion",
    brand: "Elegance",
    rating: 4.8,
    reviews: 125,
    reviewCount: 125,
    inStock: true,
    isNewArrival: false,
    isFeatured: true,
    discount: 18.6,
    freeShipping: true,
    tags: ["blazer", "tailored", "fashion", "clothing"],
  },
  {
    id: "fashion-13",
    name: "Canvas Sneakers",
    description: "Casual canvas sneakers with cushioned sole. Perfect for everyday comfort and style.",
    price: 79.99,
    originalPrice: null,
    images: [
      "/img/fashion-13-1.jpg",
      "/img/fashion-13-2.jpg",
      "/img/fashion-13-3.jpg",
      "/img/fashion-13-4.jpg",
    ],
    category: "fashion",
    brand: "SunStyle",
    rating: 4.6,
    reviews: 105,
    reviewCount: 105,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["sneakers", "canvas", "fashion", "footwear"],
  },
  {
    id: "fashion-14",
    name: "Leather Belt",
    description: "Classic leather belt with polished buckle. Versatile for formal or casual outfits.",
    price: 59.99,
    originalPrice: null,
    images: [
      "/img/fashion-14-1.jpg",
      "/img/fashion-14-2.jpg",
      "/img/fashion-14-3.jpg",
      "/img/fashion-14-4.jpg",
    ],
    category: "fashion",
    brand: "Luxe Bags",
    rating: 4.5,
    reviews: 95,
    reviewCount: 95,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["belt", "leather", "fashion", "accessory"],
  },
  {
    id: "fashion-15",
    name: "Hoop Earrings",
    description: "Elegant gold-tone hoop earrings. Lightweight and perfect for daily wear.",
    price: 49.99,
    originalPrice: null,
    images: [
      "/img/fashion-15-1.jpg",
      "/img/fashion-15-2.jpg",
      "/img/fashion-15-3.jpg",
      "/img/fashion-15-4.jpg",
    ],
    category: "fashion",
    brand: "Artisan Style",
    rating: 4.7,
    reviews: 80,
    reviewCount: 80,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["earrings", "jewelry", "fashion", "accessory"],
  },
  // Home Decor Products
  {
    id: "home-1",
    name: "Abstract Wall Art",
    description: "Modern abstract painting on canvas. Adds contemporary style and color to any room.",
    price: 199.99,
    originalPrice: null,
    images: [
      "/img/home-1-1.jpg",
      "/img/home-1-2.jpg",
      "/img/home-1-3.jpg",
      "/img/home-1-4.jpg",
    ],
    category: "home-decor",
    brand: "Art Studio",
    rating: 4.6,
    reviews: 89,
    reviewCount: 89,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["wall art", "abstract", "painting", "decor"],
  },
  {
    id: "home-2",
    name: "Table Lamp Modern",
    description:
      "Contemporary table lamp with adjustable brightness. Features sleek design and energy-efficient LED bulb.",
    price: 129.99,
    originalPrice: null,
    images: [
      "/img/home-2-1.jpg",
      "/img/home-2-2.jpg",
      "/img/home-2-3.jpg",
      "/img/home-2-4.jpg",
    ],
    category: "home-decor",
    brand: "Light Design",
    rating: 4.8,
    reviews: 112,
    reviewCount: 112,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["lamp", "lighting", "modern", "decor"],
  },
  {
    id: "home-3",
    name: "Decorative Throw Pillows",
    description:
      "Set of decorative throw pillows in coordinating colors. Made from premium fabrics with hidden zippers.",
    price: 79.99,
    originalPrice: 99.99,
    images: [
      "/img/home-3-1.jpg",
      "/img/home-3-2.jpg",
      "/img/home-3-3.jpg",
      "/img/home-3-4.jpg",
    ],
    category: "home-decor",
    brand: "Comfort Home",
    rating: 4.7,
    reviews: 145,
    reviewCount: 145,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 20,
    freeShipping: true,
    tags: ["pillows", "throw", "decorative", "home"],
  },
  {
    id: "home-4",
    name: "Ceramic Vase Set",
    description: "Set of three ceramic vases in varying sizes. Perfect for floral arrangements or decor.",
    price: 89.99,
    originalPrice: null,
    images: [
      "/img/home-4-1.jpg",
      "/img/home-4-2.jpg",
      "/img/home-4-3.jpg",
      "/img/home-4-4.jpg",
    ],
    category: "home-decor",
    brand: "Art Studio",
    rating: 4.6,
    reviews: 95,
    reviewCount: 95,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["vase", "ceramic", "decor", "home"],
  },
  {
    id: "home-5",
    name: "Woven Wall Hanging",
    description: "Handwoven wall hanging with bohemian design. Adds texture and warmth to any space.",
    price: 149.99,
    originalPrice: 179.99,
    images: [
      "/img/home-5-1.jpg",
      "/img/home-5-2.jpg",
      "/img/home-5-3.jpg",
      "/img/home-5-4.jpg",
    ],
    category: "home-decor",
    brand: "Comfort Home",
    rating: 4.7,
    reviews: 80,
    reviewCount: 80,
    inStock: true,
    isNewArrival: true,
    isFeatured: false,
    discount: 16.67,
    freeShipping: true,
    tags: ["wall hanging", "woven", "bohemian", "decor"],
  },
  {
    id: "home-6",
    name: "Marble Bookends",
    description: "Pair of polished marble bookends. Elegant and functional for organizing bookshelves.",
    price: 69.99,
    originalPrice: null,
    images: [
      "/img/home-6-1.jpg",
      "/img/home-6-2.jpg",
      "/img/home-6-3.jpg",
      "/img/home-6-4.jpg",
    ],
    category: "home-decor",
    brand: "Light Design",
    rating: 4.5,
    reviews: 70,
    reviewCount: 70,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["bookends", "marble", "decor", "home"],
  },
  {
    id: "home-7",
    name: "Velvet Curtains",
    description: "Luxurious velvet curtains in deep blue. Adds elegance and privacy to any room.",
    price: 199.99,
    originalPrice: 249.99,
    images: [
      "/img/home-7-1.jpg",
      "/img/home-7-2.jpg",
      "/img/home-7-3.jpg",
      "/img/home-7-4.jpg",
    ],
    category: "home-decor",
    brand: "Comfort Home",
    rating: 4.8,
    reviews: 100,
    reviewCount: 100,
    inStock: true,
    isNewArrival: false,
    isFeatured: true,
    discount: 20,
    freeShipping: true,
    tags: ["curtains", "velvet", "decor", "home"],
  },
  {
    id: "home-8",
    name: "Wooden Picture Frame",
    description: "Rustic wooden picture frame for 8x10 photos. Adds warmth to your decor.",
    price: 29.99,
    originalPrice: null,
    images: [
      "/img/home-8-1.jpg",
      "/img/home-8-2.jpg",
      "/img/home-8-3.jpg",
      "/img/home-8-4.jpg",
    ],
    category: "home-decor",
    brand: "Art Studio",
    rating: 4.6,
    reviews: 85,
    reviewCount: 85,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["picture frame", "wooden", "decor", "home"],
  },
  {
    id: "home-9",
    name: "Glass Candle Holder",
    description: "Elegant glass candle holder for pillar candles. Creates a warm ambiance.",
    price: 39.99,
    originalPrice: null,
    images: [
      "/img/home-9-1.jpg",
      "/img/home-9-2.jpg",
      "/img/home-9-3.jpg",
      "/img/home-9-4.jpg",
    ],
    category: "home-decor",
    brand: "Light Design",
    rating: 4.5,
    reviews: 90,
    reviewCount: 90,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["candle holder", "glass", "decor", "home"],
  },
  {
    id: "home-10",
    name: "Rattan Wall Mirror",
    description: "Round rattan wall mirror with bohemian style. Perfect for entryways or bedrooms.",
    price: 159.99,
    originalPrice: 199.99,
    images: [
      "/img/home-10-1.jpg",
      "/img/home-10-2.jpg",
      "/img/home-10-3.jpg",
      "/img/home-10-4.jpg",
    ],
    category: "home-decor",
    brand: "Art Studio",
    rating: 4.7,
    reviews: 110,
    reviewCount: 110,
    inStock: true,
    isNewArrival: true,
    isFeatured: false,
    discount: 20,
    freeShipping: true,
    tags: ["mirror", "rattan", "bohemian", "decor"],
  },
  {
    id: "home-11",
    name: "Ceramic Planter",
    description: "Matte ceramic planter for indoor plants. Adds modern style to your home.",
    price: 49.99,
    originalPrice: null,
    images: [
      "/img/home-11-1.jpg",
      "/img/home-11-2.jpg",
      "/img/home-11-3.jpg",
      "/img/home-11-4.jpg",
    ],
    category: "home-decor",
    brand: "Comfort Home",
    rating: 4.6,
    reviews: 75,
    reviewCount: 75,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["planter", "ceramic", "decor", "home"],
  },
  {
    id: "home-12",
    name: "Linen Table Runner",
    description: "Natural linen table runner with subtle texture. Elevates dining table aesthetics.",
    price: 39.99,
    originalPrice: null,
    images: [
      "/img/home-12-1.jpg",
      "/img/home-12-2.jpg",
      "/img/home-12-3.jpg",
      "/img/home-12-4.jpg",
    ],
    category: "home-decor",
    brand: "Comfort Home",
    rating: 4.5,
    reviews: 80,
    reviewCount: 80,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["table runner", "linen", "decor", "home"],
  },
  {
    id: "home-13",
    name: "Brass Wall Sconce",
    description: "Modern brass wall sconce with adjustable arm. Perfect for ambient lighting.",
    price: 129.99,
    originalPrice: 159.99,
    images: [
      "/img/home-13-1.jpg",
      "/img/home-13-2.jpg",
      "/img/home-13-3.jpg",
      "/img/home-13-4.jpg",
    ],
    category: "home-decor",
    brand: "Light Design",
    rating: 4.7,
    reviews: 95,
    reviewCount: 95,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 18.75,
    freeShipping: true,
    tags: ["wall sconce", "brass", "lighting", "decor"],
  },
  {
    id: "home-14",
    name: "Woven Storage Basket",
    description: "Large woven storage basket for blankets or toys. Adds rustic charm to any room.",
    price: 69.99,
    originalPrice: null,
    images: [
      "/img/home-14-1.jpg",
      "/img/home-14-2.jpg",
      "/img/home-14-3.jpg",
      "/img/home-14-4.jpg",
    ],
    category: "home-decor",
    brand: "Comfort Home",
    rating: 4.6,
    reviews: 85,
    reviewCount: 85,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["basket", "woven", "storage", "decor"],
  },
  {
    id: "home-15",
    name: "Framed Botanical Print",
    description: "Set of two framed botanical prints. Adds natural elegance to your walls.",
    price: 99.99,
    originalPrice: null,
    images: [
      "/img/home-15-1.jpg",
      "/img/home-15-2.jpg",
      "/img/home-15-3.jpg",
      "/img/home-15-4.jpg",
    ],
    category: "home-decor",
    brand: "Art Studio",
    rating: 4.7,
    reviews: 90,
    reviewCount: 90,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["wall art", "botanical", "framed", "decor"],
  },

  // Fitness Products
 {
    id: "fitness-1",
    name: "Adjustable Dumbbells",
    description: "Space-saving adjustable dumbbells with quick-change weight system. Perfect for home workouts.",
    price: 299.99,
    originalPrice: null,
    images: [
      "/img/fitness-1-1.jpg",
      "/img/fitness-1-2.jpg",
      "/img/fitness-1-3.jpg",
      "/img/fitness-1-4.jpg",
    ],
    category: "fitness",
    brand: "FitGear",
    rating: 4.8,
    reviews: 234,
    reviewCount: 234,
    inStock: true,
    isNewArrival: false,
    isFeatured: true,
    discount: 0,
    freeShipping: true,
    tags: ["dumbbells", "adjustable", "fitness", "strength"],
  },
  {
    id: "fitness-2",
    name: "Resistance Band Set",
    description:
      "Complete resistance band set with multiple resistance levels. Includes door anchor and exercise guide.",
    price: 49.99,
    originalPrice: 69.99,
    images: [
      "/img/fitness-2-1.jpg",
      "/img/fitness-2-2.jpg",
      "/img/fitness-2-3.jpg",
      "/img/fitness-2-4.jpg",
    ],
    category: "fitness",
    brand: "FlexFit",
    rating: 4.6,
    reviews: 178,
    reviewCount: 178,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 28.57, // (69.99 - 49.99) / 69.99 * 100 ≈ 28.57%
    freeShipping: true,
    tags: ["resistance bands", "exercise", "fitness", "portable"],
  },
  {
    id: "fitness-3",
    name: "Fitness Tracker Pro",
    description: "Advanced fitness tracker with heart rate monitoring, sleep tracking, and smartphone notifications.",
    price: 199.99,
    originalPrice: null,
    images: [
      "/img/fitness-3-1.jpg",
      "/img/fitness-3-2.jpg",
      "/img/fitness-3-3.jpg",
      "/img/fitness-3-4.jpg",
    ],
    category: "fitness",
    brand: "HealthTech",
    rating: 4.7,
    reviews: 156,
    reviewCount: 156,
    inStock: true,
    isNewArrival: true,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["fitness tracker", "health", "monitoring", "wearable"],
  },
  {
    id: "fitness-4",
    name: "Yoga Block Set",
    description: "Set of two high-density foam yoga blocks. Supports poses and enhances flexibility.",
    price: 29.99,
    originalPrice: null,
    images: [
      "/img/fitness-4-1.jpg",
      "/img/fitness-4-2.jpg",
      "/img/fitness-4-3.jpg",
      "/img/fitness-4-4.jpg",
    ],
    category: "fitness",
    brand: "FlexFit",
    rating: 4.6,
    reviews: 85,
    reviewCount: 85,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["yoga block", "fitness", "yoga", "accessory"],
  },
  {
    id: "fitness-5",
    name: "Kettlebell",
    description: "Cast iron kettlebell (20kg) for strength training and cardio workouts.",
    price: 79.99,
    originalPrice: 99.99,
    images: [
      "/img/fitness-5-1.jpg",
      "/img/fitness-5-2.jpg",
      "/img/fitness-5-3.jpg",
      "/img/fitness-5-4.jpg",
    ],
    category: "fitness",
    brand: "FitGear",
    rating: 4.7,
    reviews: 120,
    reviewCount: 120,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 20,
    freeShipping: true,
    tags: ["kettlebell", "strength", "fitness", "workout"],
  },
  {
    id: "fitness-6",
    name: "Exercise Ball",
    description: "Anti-burst exercise ball for core workouts and stability training. Includes pump.",
    price: 39.99,
    originalPrice: null,
    images: [
      "/img/fitness-6-1.jpg",
      "/img/fitness-6-2.jpg",
      "/img/fitness-6-3.jpg",
      "/img/fitness-6-4.jpg",
    ],
    category: "fitness",
    brand: "FlexFit",
    rating: 4.5,
    reviews: 90,
    reviewCount: 90,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["exercise ball", "fitness", "core", "workout"],
  },
  {
    id: "fitness-7",
    name: "Jump Rope",
    description: "Adjustable jump rope with weighted handles. Ideal for cardio and endurance training.",
    price: 24.99,
    originalPrice: null,
    images: [
      "/img/fitness-7-1.jpg",
      "/img/fitness-7-2.jpg",
      "/img/fitness-7-3.jpg",
      "/img/fitness-7-4.jpg",
    ],
    category: "fitness",
    brand: "FitGear",
    rating: 4.6,
    reviews: 100,
    reviewCount: 100,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["jump rope", "cardio", "fitness", "workout"],
  },
  {
    id: "fitness-8",
    name: "Foam Roller",
    description: "High-density foam roller for muscle recovery and flexibility. Ideal for post-workout relief.",
    price: 34.99,
    originalPrice: null,
    images: [
      "/img/fitness-8-1.jpg",
      "/img/fitness-8-2.jpg",
      "/img/fitness-8-3.jpg",
      "/img/fitness-8-4.jpg",
    ],
    category: "fitness",
    brand: "HealthTech",
    rating: 4.7,
    reviews: 95,
    reviewCount: 95,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["foam roller", "recovery", "fitness", "massage"],
  },
  {
    id: "fitness-9",
    name: "Pull-Up Bar",
    description: "Doorway pull-up bar for upper body strength training. Easy to install and remove.",
    price: 59.99,
    originalPrice: 79.99,
    images: [
      "/img/fitness-9-1.jpg",
      "/img/fitness-9-2.jpg",
      "/img/fitness-9-3.jpg",
      "/img/fitness-9-4.jpg",
    ],
    category: "fitness",
    brand: "FitGear",
    rating: 4.8,
    reviews: 130,
    reviewCount: 130,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 25,
    freeShipping: true,
    tags: ["pull-up bar", "strength", "fitness", "home gym"],
  },
  {
    id: "fitness-10",
    name: "Ab Roller",
    description: "Dual-wheel ab roller with knee pad for core strengthening exercises.",
    price: 29.99,
    originalPrice: null,
    images: [
      "/img/fitness-10-1.jpg",
      "/img/fitness-10-2.jpg",
      "/img/fitness-10-3.jpg",
      "/img/fitness-10-4.jpg",
    ],
    category: "fitness",
    brand: "FlexFit",
    rating: 4.5,
    reviews: 80,
    reviewCount: 80,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["ab roller", "core", "fitness", "workout"],
  },
  {
    id: "fitness-11",
    name: "Weighted Vest",
    description: "Adjustable weighted vest (10kg) for enhancing bodyweight workouts.",
    price: 89.99,
    originalPrice: 109.99,
    images: [
      "/img/fitness-11-1.jpg",
      "/img/fitness-11-2.jpg",
      "/img/fitness-11-3.jpg",
      "/img/fitness-11-4.jpg",
    ],
    category: "fitness",
    brand: "FitGear",
    rating: 4.7,
    reviews: 110,
    reviewCount: 110,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 18.18,
    freeShipping: true,
    tags: ["weighted vest", "fitness", "strength", "workout"],
  },
  {
    id: "fitness-12",
    name: "Balance Board",
    description: "Wooden balance board for core strength and stability training.",
    price: 69.99,
    originalPrice: null,
    images: [
      "/img/fitness-12-1.jpg",
      "/img/fitness-12-2.jpg",
      "/img/fitness-12-3.jpg",
      "/img/fitness-12-4.jpg",
    ],
    category: "fitness",
    brand: "HealthTech",
    rating: 4.6,
    reviews: 75,
    reviewCount: 75,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: true,
    tags: ["balance board", "core", "fitness", "stability"],
  },
  {
    id: "fitness-13",
    name: "Ankle Weights",
    description: "Set of two adjustable ankle weights (2kg each) for resistance training.",
    price: 39.99,
    originalPrice: null,
    images: [
      "/img/fitness-13-1.jpg",
      "/img/fitness-13-2.jpg",
      "/img/fitness-13-3.jpg",
      "/img/fitness-13-4.jpg",
    ],
    category: "fitness",
    brand: "FlexFit",
    rating: 4.5,
    reviews: 70,
    reviewCount: 70,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 0,
    freeShipping: false,
    tags: ["ankle weights", "resistance", "fitness", "workout"],
  },
  {
    id: "fitness-14",
    name: "Massage Gun",
    description: "Portable massage gun with multiple speed settings for muscle recovery.",
    price: 129.99,
    originalPrice: 179.99,
    images: [
      "/img/fitness-14-1.jpg",
      "/img/fitness-14-2.jpg",
      "/img/fitness-14-3.jpg",
      "/img/fitness-14-4.jpg",
    ],
    category: "fitness",
    brand: "HealthTech",
    rating: 4.9,
    reviews: 140,
    reviewCount: 140,
    inStock: true,
    isNewArrival: true,
    isFeatured: true,
    discount: 27.78,
    freeShipping: true,
    tags: ["massage gun", "recovery", "fitness", "massage"],
  },
  {
    id: "fitness-15",
    name: "Premium Yoga Mat",
    description: "Non-slip yoga mat made from natural rubber. Provides excellent grip and cushioning.",
    price: 89.99,
    originalPrice: null,
    images: [
      "/img/fitness-15-1.jpg",
      "/img/fitness-15-2.jpg",
      "/img/fitness-15-3.jpg",
      "/img/fitness-15-4.jpg",
    ],
    category: "fitness",
    brand: "FlexFit",
    rating: 4.8,
    reviews: 165,
    reviewCount: 165,
    inStock: true,
    isNewArrival: false,
    isFeatured: true,
    discount: 0,
    freeShipping: true,
    tags: ["yoga mat", "fitness", "yoga", "exercise"],
  },
]

// Categories data
const categories: Category[] = [
  {
    id: "lifestyle",
    name: "Lifestyle",
    slug: "lifestyle",
    description: "Curated essentials for modern living",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=600&fit=crop",
    productCount: 120,
    featured: true,
  },
  {
    id: "wellness",
    name: "Wellness",
    slug: "wellness",
    description: "Products for mind, body, and soul",
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&h=600&fit=crop",
    productCount: 85,
    featured: true,
  },
  {
    id: "electronics",
    name: "Electronics",
    slug: "electronics",
    description: "Cutting-edge technology and smart devices",
    image: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=800&h=600&fit=crop",
    productCount: 95,
    featured: true,
  },
  {
    id: "fashion",
    name: "Fashion",
    slug: "fashion",
    description: "Timeless pieces and contemporary styles",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=600&fit=crop",
    productCount: 200,
    featured: true,
  },
  {
    id: "home-decor",
    name: "Home Decor",
    slug: "home-decor",
    description: "Transform your living space",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=600&fit=crop",
    productCount: 150,
    featured: true,
  },
  {
    id: "fitness",
    name: "Fitness",
    slug: "fitness",
    description: "Premium fitness equipment and accessories",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop",
    productCount: 75,
    featured: true,
  },
]

// Helper functions
export async function getAllProducts(): Promise<Product[]> {
  return products
}

export async function getProductById(id: string): Promise<Product | null> {
  return products.find((product) => product.id === id) || null
}

export async function getProductsByCategory(category: string): Promise<Product[]> {
  return products.filter((product) => product.category === category)
}

export async function getFeaturedProducts(): Promise<Product[]> {
  return products.filter((product) => product.isFeatured).slice(0, 8)
}

export async function getNewArrivals(): Promise<Product[]> {
  return products.filter((product) => product.isNewArrival).slice(0, 8)
}

export async function searchProducts(query: string): Promise<Product[]> {
  const lowercaseQuery = query.toLowerCase()
  return products.filter(
    (product) =>
      product.name.toLowerCase().includes(lowercaseQuery) ||
      product.description.toLowerCase().includes(lowercaseQuery) ||
      product.brand.toLowerCase().includes(lowercaseQuery) ||
      product.category.toLowerCase().includes(lowercaseQuery) ||
      product.tags?.some((tag) => tag.toLowerCase().includes(lowercaseQuery)),
  )
}

export async function getRelatedProducts(productId: string, category: string): Promise<Product[]> {
  return products.filter((product) => product.id !== productId && product.category === category).slice(0, 4)
}

export async function getAllCategories(): Promise<Category[]> {
  return categories
}

export async function getCategoryBySlug(slug: string): Promise<Category | null> {
  return categories.find((category) => category.slug === slug) || null
}
