import type { Product, Category } from "./types"

// Mock product data with all categories
const products: Product[] = [
  // Lifestyle Products
  {
    id: "lifestyle-1",
    name: "Minimalist Ceramic Vase",
    description:
      "Handcrafted ceramic vase with clean lines and modern aesthetic. Perfect for fresh flowers or as a standalone decorative piece.",
    price: 89.99,
    originalPrice: 119.99,
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=500&h=500&fit=crop",
    category: "lifestyle",
    brand: "Nordic Home",
    rating: 4.8,
    reviews: 124,
    reviewCount: 124,
    inStock: true,
    isNewArrival: true,
    isFeatured: true,
    discount: 25,
    freeShipping: true,
    tags: ["ceramic", "vase", "minimalist", "home decor"],
  },
  {
    id: "lifestyle-2",
    name: "Luxury Cashmere Throw",
    description: "Ultra-soft cashmere throw blanket in neutral tones. Adds warmth and elegance to any living space.",
    price: 299.99,
    originalPrice: 399.99,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&h=500&fit=crop",
    category: "lifestyle",
    brand: "Comfort Co",
    rating: 4.9,
    reviews: 89,
    reviewCount: 89,
    inStock: true,
    isFeatured: true,
    discount: 25,
    freeShipping: true,
    tags: ["cashmere", "throw", "blanket", "luxury"],
  },
  {
    id: "lifestyle-3",
    name: "Brass Mirror Round",
    description: "Elegant round mirror with brass frame. Perfect for entryways, bathrooms, or as an accent piece.",
    price: 159.99,
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&h=500&fit=crop",
    category: "lifestyle",
    brand: "Reflection",
    rating: 4.7,
    reviews: 67,
    reviewCount: 67,
    inStock: true,
    freeShipping: true,
    tags: ["mirror", "brass", "round", "decor"],
  },
  {
    id: "lifestyle-4",
    name: "Walnut Coffee Table",
    description:
      "Mid-century modern coffee table crafted from solid walnut wood. Features clean lines and timeless design.",
    price: 899.99,
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&h=500&fit=crop",
    category: "lifestyle",
    brand: "Wood Works",
    rating: 4.8,
    reviews: 45,
    reviewCount: 45,
    inStock: true,
    freeShipping: true,
    tags: ["coffee table", "walnut", "mid-century", "furniture"],
  [
    }, 
  {
    id: "lifestyle-5",
    name: "Handwoven Jute Rug",
    description: "Natural jute rug with intricate weave patterns, adding texture and warmth to any room.",
    price: 249.99,
    originalPrice: 299.99,
    image: "https://images.unsplash.com/photo-1591343395082-6d3e7d6b8e8a?w=500&h=500&fit=crop",
    category: "lifestyle",
    brand: "Earthy Threads",
    rating: 4.6,
    reviews: 78,
    reviewCount: 78,
    inStock: true,
    isNewArrival: false,
    isFeatured: false,
    discount: 16.67,
    freeShipping: true,
    tags: ["rug", "jute", "handwoven", "home decor"]
  },
  {
    id: "lifestyle-6",
    name: "Marble Coaster Set",
    description: "Set of four polished marble coasters with gold accents, perfect for protecting surfaces in style.",
    price: 39.99,
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=500&h=500&fit=crop",
    category: "lifestyle",
    brand: "Stone Elegance",
    rating: 4.5,
    reviews: 102,
    reviewCount: 102,
    inStock: true,
    freeShipping: false,
    tags: ["coasters", "marble", "gold accent", "tableware"]
  },
  {
    id: "lifestyle-7",
    name: "Velvet Accent Pillow",
    description: "Luxurious velvet pillow in deep emerald green, adding a pop of color and comfort to sofas or beds.",
    price: 59.99,
    originalPrice: 79.99,
    image: "https://images.unsplash.com/photo-1578898886223-6e609b0e65d0?w=500&h=500&fit=crop",
    category: "lifestyle",
    brand: "Comfort Co",
    rating: 4.7,
    reviews: 56,
    reviewCount: 56,
    inStock: true,
    isFeatured: true,
    discount: 25,
    freeShipping: true,
    tags: ["pillow", "velvet", "accent", "home decor"]
  },
  {
    id: "lifestyle-8",
    name: "Bamboo Wall Shelf",
    description: "Minimalist bamboo wall shelf, ideal for displaying plants, books, or decorative items.",
    price: 129.99,
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=500&h=500&fit=crop",
    category: "lifestyle",
    brand: "Eco Living",
    rating: 4.4,
    reviews: 33,
    reviewCount: 33,
    inStock: true,
    freeShipping: true,
    tags: ["shelf", "bamboo", "wall decor", "storage"]
  },
  {
    id: "lifestyle-9",
    name: "Scented Soy Candle",
    description: "Hand-poured soy candle with lavender and cedarwood notes, housed in a sleek glass jar.",
    price: 29.99,
    image: "https://images.unsplash.com/photo-1603006905003-3e7c8b2e6d0a?w=500&h=500&fit=crop",
    category: "lifestyle",
    brand: "Glow Essence",
    rating: 4.9,
    reviews: 145,
    reviewCount: 145,
    inStock: true,
    isNewArrival: true,
    freeShipping: false,
    tags: ["candle", "soy", "scented", "home decor"]
  },
  {
    id: "lifestyle-10",
    name: "Linen Bedding Set",
    description: "Breathable linen bedding set in soft ivory, including duvet cover and two pillowcases.",
    price: 349.99,
    originalPrice: 429.99,
    image: "https://images.unsplash.com/photo-1584100936595-3704e3f6a9b2?w=500&h=500&fit=crop",
    category: "lifestyle",
    brand: "Pure Rest",
    rating: 4.8,
    reviews: 92,
    reviewCount: 92,
    inStock: true,
    isFeatured: true,
    discount: 18.6,
    freeShipping: true,
    tags: ["bedding", "linen", "duvet", "bedroom"]
  },
  {
    id: "lifestyle-11",
    name: "Terrazzo Side Table",
    description: "Modern terrazzo side table with a speckled finish, perfect for small spaces or as a bedside accent.",
    price: 199.99,
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&h=500&fit=crop",
    category: "lifestyle",
    brand: "Urban Craft",
    rating: 4.6,
    reviews: 64,
    reviewCount: 64,
    inStock: true,
    freeShipping: true,
    tags: ["side table", "terrazzo", "modern", "furniture"]
  },
  {
    id: "lifestyle-12",
    name: "Ceramic Table Lamp",
    description: "Sculptural ceramic table lamp with a matte finish and linen shade, ideal for cozy lighting.",
    price: 139.99,
    image: "https://images.unsplash.com/photo-1586105251261-72a756497a11?w=500&h=500&fit=crop",
    category: "lifestyle",
    brand: "Light Haven",
    rating: 4.7,
    reviews: 88,
    reviewCount: 88,
    inStock: true,
    freeShipping: true,
    tags: ["lamp", "ceramic", "lighting", "home decor"]
  },
  {
    id: "lifestyle-13",
    name: "Woven Basket Set",
    description: "Set of three woven seagrass baskets for stylish storage of blankets, toys, or plants.",
    price: 79.99,
    image: "https://images.unsplash.com/photo-1598928636135-d146006ff4be?w=500&h=500&fit=crop",
    category: "lifestyle",
    brand: "Natural Nest",
    rating: 4.5,
    reviews: 47,
    reviewCount: 47,
    inStock: true,
    freeShipping: false,
    tags: ["basket", "seagrass", "storage", "home decor"]
  },
  {
    id: "lifestyle-14",
    name: "Glass Decanter Set",
    description: "Elegant glass decanter with two matching glasses, perfect for serving whiskey or wine.",
    price: 99.99,
    originalPrice: 129.99,
    image: "https://images.unsplash.com/photo-1598965402083-8e0f7e0c5c5e?w=500&h=500&fit=crop",
    category: "lifestyle",
    brand: "Crystal Craft",
    rating: 4.8,
    reviews: 76,
    reviewCount: 76,
    inStock: true,
    isNewArrival: true,
    discount: 23.08,
    freeShipping: true,
    tags: ["decanter", "glassware", "barware", "luxury"]
  },
  {
    id: "lifestyle-15",
    name: "Teak Wood Cutting Board",
    description: "Durable teak wood cutting board with natural grain, perfect for food prep or serving.",
    price: 49.99,
    image: "https://images.unsplash.com/photo-1585861026776-3f4a1e8e6e6e?w=500&h=500&fit=crop",
    category: "lifestyle",
    brand: "Kitchen Essence",
    rating: 4.6,
    reviews: 112,
    reviewCount: 112,
    inStock: true,
    freeShipping: false,
    tags: ["cutting board", "teak", "kitchen", "serveware"]
  },
  {
    id: "lifestyle-16",
    name: "Velvet Ottoman",
    description: "Plush velvet ottoman in navy blue, doubling as a footrest or extra seating.",
    price: 249.99,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&h=500&fit=crop",
    category: "lifestyle",
    brand: "Urban Comfort",
    rating: 4.7,
    reviews: 53,
    reviewCount: 53,
    inStock: true,
    freeShipping: true,
    tags: ["ottoman", "velvet", "furniture", "home decor"]
  },
  {
    id: "lifestyle-17",
    name: "Framed Abstract Art Print",
    description: "Bold abstract art print in a sleek black frame, perfect for modern interiors.",
    price: 179.99,
    originalPrice: 229.99,
    image: "https://images.unsplash.com/photo-1579546929662-711aa81148cf?w=500&h=500&fit=crop",
    category: "lifestyle",
    brand: "Artisan Gallery",
    rating: 4.8,
    reviews: 69,
    reviewCount: 69,
    inStock: true,
    isFeatured: true,
    discount: 21.74,
    freeShipping: true,
    tags: ["art print", "abstract", "framed", "wall decor"]
  },
  {
    id: "lifestyle-18",
    name: "Stainless Steel Water Bottle",
    description: "Sleek stainless steel water bottle with double-wall insulation, keeping drinks hot or cold for hours.",
    price: 34.99,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500&h=500&fit=crop",
    category: "lifestyle",
    brand: "Eco Sip",
    rating: 4.5,
    reviews: 134,
    reviewCount: 134,
    inStock: true,
    freeShipping: false,
    tags: ["water bottle", "stainless steel", "insulated", "eco-friendly"]
  },
  {
    id: "lifestyle-19",
    name: "Rattan Armchair",
    description: "Handcrafted rattan armchair with a cushioned seat, blending bohemian and modern styles.",
    price: 499.99,
    image: "https://images.unsplash.com/photo-1592078615290-033ee584e267?w=500&h=500&fit=crop",
    category: "lifestyle",
    brand: "Boho Living",
    rating: 4.9,
    reviews: 41,
    reviewCount: 41,
    inStock: true,
    freeShipping: true,
    tags: ["armchair", "rattan", "bohemian", "furniture"]
  },

  // Wellness Products
  {
    id: "wellness-1",
    name: "Essential Oil Diffuser",
    description:
      "Ultrasonic aromatherapy diffuser with LED lighting. Creates a calming atmosphere while dispersing your favorite essential oils.",
    price: 79.99,
    originalPrice: 99.99,
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500&h=500&fit=crop",
    category: "wellness",
    brand: "Zen Living",
    rating: 4.6,
    reviews: 203,
    reviewCount: 203,
    inStock: true,
    isFeatured: true,
    discount: 20,
    freeShipping: true,
    tags: ["diffuser", "aromatherapy", "wellness", "essential oils"],
  },
  {
    id: "wellness-2",
    name: "Premium Yoga Mat",
    description:
      "Non-slip yoga mat made from natural rubber. Provides excellent grip and cushioning for all yoga practices.",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500&h=500&fit=crop",
    category: "wellness",
    brand: "Mindful Movement",
    rating: 4.8,
    reviews: 156,
    reviewCount: 156,
    inStock: true,
    isFeatured: true,
    freeShipping: true,
    tags: ["yoga", "mat", "exercise", "wellness"],
  },
  {
    id: "wellness-3",
    name: "Meditation Cushion",
    description:
      "Comfortable meditation cushion filled with buckwheat hulls. Supports proper posture during meditation practice.",
    price: 59.99,
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=500&h=500&fit=crop",
    category: "wellness",
    brand: "Inner Peace",
    rating: 4.7,
    reviews: 92,
    reviewCount: 92,
    inStock: true,
    freeShipping: true,
    tags: ["meditation", "cushion", "mindfulness", "wellness"],
  },

  // Electronics Products
  {
    id: "electronics-1",
    name: "Wireless Noise-Canceling Headphones",
    description:
      "Premium wireless headphones with active noise cancellation. Delivers exceptional sound quality and comfort.",
    price: 299.99,
    originalPrice: 399.99,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=500&fit=crop",
    category: "electronics",
    brand: "SoundTech",
    rating: 4.9,
    reviews: 342,
    reviewCount: 342,
    inStock: true,
    isFeatured: true,
    discount: 25,
    freeShipping: true,
    tags: ["headphones", "wireless", "noise-canceling", "audio"],
  },
  {
    id: "electronics-2",
    name: "Smart Fitness Watch",
    description:
      "Advanced fitness tracker with heart rate monitoring, GPS, and smartphone connectivity. Perfect for active lifestyles.",
    price: 249.99,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&h=500&fit=crop",
    category: "electronics",
    brand: "FitTech",
    rating: 4.7,
    reviews: 189,
    reviewCount: 189,
    inStock: true,
    isNewArrival: true,
    freeShipping: true,
    tags: ["smartwatch", "fitness", "tracker", "health"],
  },
  {
    id: "electronics-3",
    name: "Portable Bluetooth Speaker",
    description:
      "Compact wireless speaker with powerful sound and long battery life. Perfect for outdoor adventures and home use.",
    price: 129.99,
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500&h=500&fit=crop",
    category: "electronics",
    brand: "AudioWave",
    rating: 4.6,
    reviews: 267,
    reviewCount: 267,
    inStock: true,
    freeShipping: true,
    tags: ["speaker", "bluetooth", "portable", "audio"],
  },

  // Fashion Products
  {
    id: "fashion-1",
    name: "Silk Scarf Collection",
    description: "Luxurious silk scarf with hand-painted design. Adds elegance to any outfit and makes a perfect gift.",
    price: 149.99,
    originalPrice: 199.99,
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=500&h=500&fit=crop",
    category: "fashion",
    brand: "Elegance",
    rating: 4.8,
    reviews: 78,
    reviewCount: 78,
    inStock: true,
    discount: 25,
    freeShipping: true,
    tags: ["scarf", "silk", "fashion", "accessory"],
  },
  {
    id: "fashion-2",
    name: "Designer Handbag",
    description: "Premium leather handbag with modern design. Features multiple compartments and adjustable strap.",
    price: 399.99,
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=500&h=500&fit=crop",
    category: "fashion",
    brand: "Luxe Bags",
    rating: 4.9,
    reviews: 134,
    reviewCount: 134,
    inStock: true,
    isFeatured: true,
    freeShipping: true,
    tags: ["handbag", "leather", "designer", "fashion"],
  },
  {
    id: "fashion-3",
    name: "Polarized Sunglasses",
    description:
      "Stylish sunglasses with polarized lenses and UV protection. Perfect for outdoor activities and fashion.",
    price: 179.99,
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=500&h=500&fit=crop",
    category: "fashion",
    brand: "SunStyle",
    rating: 4.7,
    reviews: 156,
    reviewCount: 156,
    inStock: true,
    isNewArrival: true,
    freeShipping: true,
    tags: ["sunglasses", "polarized", "fashion", "accessory"],
  },

  // Home Decor Products
  {
    id: "home-1",
    name: "Abstract Wall Art",
    description: "Modern abstract painting on canvas. Adds contemporary style and color to any room.",
    price: 199.99,
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&h=500&fit=crop",
    category: "home-decor",
    brand: "Art Studio",
    rating: 4.6,
    reviews: 89,
    reviewCount: 89,
    inStock: true,
    freeShipping: true,
    tags: ["wall art", "abstract", "painting", "decor"],
  },
  {
    id: "home-2",
    name: "Table Lamp Modern",
    description:
      "Contemporary table lamp with adjustable brightness. Features sleek design and energy-efficient LED bulb.",
    price: 129.99,
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&h=500&fit=crop",
    category: "home-decor",
    brand: "Light Design",
    rating: 4.8,
    reviews: 112,
    reviewCount: 112,
    inStock: true,
    freeShipping: true,
    tags: ["lamp", "lighting", "modern", "decor"],
  },
  {
    id: "home-3",
    name: "Decorative Throw Pillows",
    description:
      "Set of decorative throw pillows in coordinating colors. Made from premium fabrics with hidden zippers.",
    price: 79.99,
    originalPrice: 99.99,
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&h=500&fit=crop",
    category: "home-decor",
    brand: "Comfort Home",
    rating: 4.7,
    reviews: 145,
    reviewCount: 145,
    inStock: true,
    discount: 20,
    freeShipping: true,
    tags: ["pillows", "throw", "decorative", "home"],
  },

  // Fitness Products
  {
    id: "fitness-1",
    name: "Adjustable Dumbbells",
    description: "Space-saving adjustable dumbbells with quick-change weight system. Perfect for home workouts.",
    price: 299.99,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&h=500&fit=crop",
    category: "fitness",
    brand: "FitGear",
    rating: 4.8,
    reviews: 234,
    reviewCount: 234,
    inStock: true,
    isFeatured: true,
    freeShipping: true,
    tags: ["dumbbells", "adjustable", "fitness", "strength"],
  },
  {
    id: "fitness-2",
    name: "Resistance Band Set",
    description:
      "Complete resistance band set with multiple resistance levels. Includes door anchor and exercise guide.",
    price: 49.99,
    originalPrice: 69.99,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&h=500&fit=crop",
    category: "fitness",
    brand: "FlexFit",
    rating: 4.6,
    reviews: 178,
    reviewCount: 178,
    inStock: true,
    discount: 29,
    freeShipping: true,
    tags: ["resistance bands", "exercise", "fitness", "portable"],
  },
  {
    id: "fitness-3",
    name: "Fitness Tracker Pro",
    description: "Advanced fitness tracker with heart rate monitoring, sleep tracking, and smartphone notifications.",
    price: 199.99,
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&h=500&fit=crop",
    category: "fitness",
    brand: "HealthTech",
    rating: 4.7,
    reviews: 156,
    reviewCount: 156,
    inStock: true,
    isNewArrival: true,
    freeShipping: true,
    tags: ["fitness tracker", "health", "monitoring", "wearable"],
  },
]

// Categories data
const categories: Category[] = [
  {
    id: "lifestyle",
    name: "Lifestyle",
    slug: "lifestyle",
    description: "Curated essentials for modern living",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=600&fit=crop",
    productCount: 120,
    featured: true,
  },
  {
    id: "wellness",
    name: "Wellness",
    slug: "wellness",
    description: "Products for mind, body, and soul",
    image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800&h=600&fit=crop",
    productCount: 85,
    featured: true,
  },
  {
    id: "electronics",
    name: "Electronics",
    slug: "electronics",
    description: "Cutting-edge technology and smart devices",
    image: "https://images.unsplash.com/photo-1498049794561-7780e7231661?w=800&h=600&fit=crop",
    productCount: 95,
    featured: true,
  },
  {
    id: "fashion",
    name: "Fashion",
    slug: "fashion",
    description: "Timeless pieces and contemporary styles",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&h=600&fit=crop",
    productCount: 200,
    featured: true,
  },
  {
    id: "home-decor",
    name: "Home Decor",
    slug: "home-decor",
    description: "Transform your living space",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&h=600&fit=crop",
    productCount: 150,
    featured: true,
  },
  {
    id: "fitness",
    name: "Fitness",
    slug: "fitness",
    description: "Premium fitness equipment and accessories",
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop",
    productCount: 75,
    featured: true,
  },
]

// Helper functions
export async function getAllProducts(): Promise<Product[]> {
  return products
}

export async function getProductById(id: string): Promise<Product | null> {
  return products.find((product) => product.id === id) || null
}

export async function getProductsByCategory(category: string): Promise<Product[]> {
  return products.filter((product) => product.category === category)
}

export async function getFeaturedProducts(): Promise<Product[]> {
  return products.filter((product) => product.isFeatured).slice(0, 8)
}

export async function getNewArrivals(): Promise<Product[]> {
  return products.filter((product) => product.isNewArrival).slice(0, 8)
}

export async function searchProducts(query: string): Promise<Product[]> {
  const lowercaseQuery = query.toLowerCase()
  return products.filter(
    (product) =>
      product.name.toLowerCase().includes(lowercaseQuery) ||
      product.description.toLowerCase().includes(lowercaseQuery) ||
      product.brand.toLowerCase().includes(lowercaseQuery) ||
      product.category.toLowerCase().includes(lowercaseQuery) ||
      product.tags?.some((tag) => tag.toLowerCase().includes(lowercaseQuery)),
  )
}

export async function getRelatedProducts(productId: string, category: string): Promise<Product[]> {
  return products.filter((product) => product.id !== productId && product.category === category).slice(0, 4)
}

export async function getAllCategories(): Promise<Category[]> {
  return categories
}

export async function getCategoryBySlug(slug: string): Promise<Category | null> {
  return categories.find((category) => category.slug === slug) || null
}
